apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: shabil/auth
                  readinessProbe:
                      exec:
                          command:
                              - /bin/sh
                              - -c
                              - |
                                  # Check if Kafka is reachable
                                  if nc -z kafka-service 9092; then
                                    exit 0
                                  else
                                    exit 1
                                  fi
                      initialDelaySeconds: 5
                      periodSeconds: 1
                  env:
                      - name: MONGO_URI
                        value: "mongodb://auth-mongo-srv:27017/auth"
                      - name: JWT_KEY
                          valueFrom:
                            secretKeyRef:
                              name: jwt-secret
                              key: JWT_KEY
                      - name: JWT_ACCESSTOKEN_EXPIRESIN
                          value: 1d
                      - name: MAIL_PASS
                          valueFrom:
                            secretKeyRef:
                              name: mail-pass
                              key: MAIL_PASS
                      - name: MAIL
                          valueFrom:
                            secretKeyRef:
                              name: mail
                              key: MAIL
                      - name: CLIENT_URI
                          valueFrom:
                            secretKeyRef:
                              name: client-uri
                              key: CLIENT_URI
                      - name: CORS_ORIGIN
                          valueFrom:
                            secretKeyRef:
                              name: cors-origin
                              key: CORS_ORIGIN
---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 3000
          targetPort: 3000
