apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            labels:
                app: client
        spec:
            containers:
                - name: client
                  image: shabil/client:latest
                  imagePullPolicy: Always
                  env:
                      - name: NEXT_PUBLIC_BASE_URL
                        value: https://quick-hire.live
                      - name: NEXT_PUBLIC_STRIPE_SOCKET_URL
                        value: https://socket.quick-hire.live/api/chats/socket
---
apiVersion: v1
kind: Service
metadata:
    name: client-srv
spec:
    selector:
        app: client
    ports:
        - name: client
          protocol: TCP
          port: 3000
          targetPort: 3000
