apiVersion: apps/v1
kind: Deployment
metadata:
    name: jobs-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jobs
    template:
        metadata:
            labels:
                app: jobs
        spec:
            containers:
                - name: jobs
                  image: shabil/jobs
                  env:
                      - name: POSTGRES_URI
                        value: postgres://user:pass@jobs-postgres-srv:5432/jobs
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
                      - name: AWS_BUCKET_NAME
                        valueFrom:
                            secretKeyRef:
                                name: bucket-name
                                key: AWS_BUCKET_NAME
                      - name: AWS_BUCKET_REGION
                        valueFrom:
                            secretKeyRef:
                                name: bucket-region
                                key: AWS_BUCKET_REGION
                      - name: AWS_S3_ACCESSKEY
                        valueFrom:
                            secretKeyRef:
                                name: s3-access-key
                                key: AWS_S3_ACCESSKEY
                      - name: AWS_S3_SECRETKEY
                        valueFrom:
                            secretKeyRef:
                                name: s3-secret-key
                                key: AWS_S3_SECRETKEY
                      - name: CORS_ORIGIN
                        valueFrom:
                            secretKeyRef:
                                name: cors-origin
                                key: CORS_ORIGIN
---
apiVersion: v1
kind: Service
metadata:
    name: jobs-srv
spec:
    selector:
        app: jobs
    ports:
        - name: jobs
          protocol: TCP
          port: 3000
          targetPort: 3000
