apiVersion: apps/v1
kind: Deployment
metadata:
    name: payments-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payments
    template:
        metadata:
            labels:
                app: payments
        spec:
            containers:
                - name: payments
                  image: shabil/payments
                  env:
                      - name: MONGO_URI
                        value: "mongodb://payments-mongo-srv:27017/payments"
                      - name: JWT_KEY
                          valueFrom:
                            secretKeyRef:
                              name: jwt-secret
                              key: JWT_KEY
                      - name: STRIPE_PRIVATE_KEY
                          valueFrom:
                            secretKeyRef:
                              name: stripe-private-key
                              key: STRIPE_PRIVATE_KEY
                      - name: END_POINT_SECRET
                          valueFrom:
                            secretKeyRef:
                              name: end-point-secret
                              key: END_POINT_SECRET
                      - name: CORS_ORIGIN
                          valueFrom:
                            secretKeyRef:
                              name: cors-origin
                              key: CORS_ORIGIN
---
apiVersion: v1
kind: Service
metadata:
    name: payments-srv
spec:
    selector:
        app: payments
    ports:
        - name: payments
          protocol: TCP
          port: 3000
          targetPort: 3000
