name: deploy-jobs

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build and push to push docker hub
              uses: actions/checkout@v2
            - run: cd jobs && docker build -t shabil/jobs .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push shabil/jobs
            - uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
            - run: doctl kubernetes cluster kubeconfig save quick-hire
            - run: kubectl rollout restart deployment jobs-depl
